/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apexListAnalyzers } from "../../funcs/apexListAnalyzers.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$apexListAnalyzers: ToolDefinition = {
  name: "apex_list-analyzers",
  description: `List of all available analyzers.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await apexListAnalyzers(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
