/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { AcuvityCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { MCPScope, mcpScopes } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$apexListAnalyzers } from "./tools/apexListAnalyzers.js";
import { tool$apexScanRequest } from "./tools/apexScanRequest.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
  apexDomain?: SDKOptions["apexDomain"] | undefined;
  apexPort?: SDKOptions["apexPort"] | undefined;
}) {
  const server = new McpServer({
    name: "Acuvity",
    version: "0.6.0",
  });

  const client = new AcuvityCore({
    security: deps.security,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
    apexDomain: deps.apexDomain,
    apexPort: deps.apexPort,
  });
  const scopes = new Set(deps.scopes ?? mcpScopes);
  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );

  tool(tool$apexListAnalyzers);
  tool(tool$apexScanRequest);

  return server;
}
