/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Apex } from "./apex.js";

export class Acuvity extends ClientSDK {
  private _apex?: Apex;
  get apex(): Apex {
    return (this._apex ??= new Apex(this._options));
  }
}
