workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Acuvity-OAS:
        inputs:
            - location: ./apex-openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/acuvity-9dx/acuvity/acuvity-oas
targets:
    typescript:
        target: typescript
        source: Acuvity-OAS
        output: .
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/acuvity-9dx/acuvity/acuvity-oas-typescript-code-samples
            blocking: false
