workflowVersion: 1.0.0
# TODO: latest Speakeasy versions are breaking our code integration
# We need to adjust this before we can update the Speakeasy version again
speakeasyVersion: 1.509.1
sources:
    Acuvity-OAS:
        inputs:
            - location: https://api.acuvity.dev/apex/v1/openapi.json?extensions=true
        registry:
            location: registry.speakeasyapi.dev/acuvity/acuvity/acuvity-oas
targets:
    typescript:
        target: typescript
        source: Acuvity-OAS
        output: .
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/acuvity/acuvity/acuvity-oas-typescript-code-samples
            blocking: false
