// This file has been autogenerated using elemental cli. 
// Use `npm run sync` to update from latest elemental specifications

import { PropertyDetails } from '../utils/const';
import { createFindErrorForIdentity, createValidateIdentity } from '../utils/validate';

/**
 * The name of the model.
 */
export type Name = string | null;
/**
 * The revision of the model.
 */
export type Revision = string | null;

/**
 * Represent an analyzer model.
 */
export interface AnalyzerModel {
  name?: Name;
  revision?: Revision;
}


// createValidateIdentity<AnalyzerModel> creates a validator for the the elemental identity AnalyzerModel
export const validateAnalyzerModel = createValidateIdentity<AnalyzerModel>('analyzermodel');

export const AnalyzerModelProperties: Record<keyof AnalyzerModel, PropertyDetails> = {
  "name": {
    "description": "The name of the model.",
    "title": "Name",
    "type": [
      "string",
      "null"
    ]
  },
  "revision": {
    "description": "The revision of the model.",
    "title": "Revision",
    "type": [
      "string",
      "null"
    ]
  },
}

// AnalyzerModelIdentity
export const AnalyzerModelIdentity = {
  isIdentity: true,
  description: `Represent an analyzer model.`,
  title: `AnalyzerModel`,
  friendlyName: `Analyzer Model`,
  friendlyNamePlural: `Analyzer Models`,
  name: 'AnalyzerModel',
  restName: 'analyzermodel',
  resourceName: 'analyzermodels',
  package: 'lain',
  archivable: false,
  findErrorForIdentity: createFindErrorForIdentity('analyzermodel'),
  properties: AnalyzerModelProperties,
} as const;
