// This file has been autogenerated using elemental cli. 
// Use `npm run sync` to update from latest elemental specifications

import { PropertyDetails } from '../utils/const';
import { createFindErrorForIdentity, createValidateIdentity } from '../utils/validate';

/**
 * How much time it took to run the access policy in nanoseconds.
 */
export type AccessPolicy = number | null;
/**
 * How much time it took to run content analysis in nanoseconds.
 */
export type Analysis = number | null;
/**
 * How much time it took to run the assign policy in nanoseconds.
 */
export type AssignPolicy = number | null;
/**
 * How much time it took to run content policy in nanoseconds.
 */
export type ContentPolicy = number | null;
/**
 * How much time it took to run input or output extraction in nanoseconds.
 */
export type Extraction = number | null;

/**
 * Holds information about latencies introduced by Apex.
 */
export interface Latency {
  accessPolicy?: AccessPolicy;
  analysis?: Analysis;
  assignPolicy?: AssignPolicy;
  contentPolicy?: ContentPolicy;
  extraction?: Extraction;
}


// createValidateIdentity<Latency> creates a validator for the the elemental identity Latency
export const validateLatency = createValidateIdentity<Latency>('latency');

export const LatencyProperties: Record<keyof Latency, PropertyDetails> = {
  "accessPolicy": {
    "description": "How much time it took to run the access policy in nanoseconds.",
    "title": "Access Policy",
    "type": [
      "integer",
      "null"
    ]
  },
  "analysis": {
    "description": "How much time it took to run content analysis in nanoseconds.",
    "title": "Analysis",
    "type": [
      "integer",
      "null"
    ]
  },
  "assignPolicy": {
    "description": "How much time it took to run the assign policy in nanoseconds.",
    "title": "Assign Policy",
    "type": [
      "integer",
      "null"
    ]
  },
  "contentPolicy": {
    "description": "How much time it took to run content policy in nanoseconds.",
    "title": "Content Policy",
    "type": [
      "integer",
      "null"
    ]
  },
  "extraction": {
    "description": "How much time it took to run input or output extraction in nanoseconds.",
    "title": "Extraction",
    "type": [
      "integer",
      "null"
    ]
  },
}

// LatencyIdentity
export const LatencyIdentity = {
  isIdentity: true,
  description: `Holds information about latencies introduced by Apex.`,
  title: `Latency`,
  friendlyName: `Latency`,
  friendlyNamePlural: `Latencies`,
  name: 'Latency',
  restName: 'latency',
  resourceName: 'latencies',
  package: 'lain',
  archivable: false,
  findErrorForIdentity: createFindErrorForIdentity('latency'),
  properties: LatencyProperties,
} as const;
