// This file has been autogenerated using elemental cli. 
// Use `npm run sync` to update from latest elemental specifications

import { PropertyDetails } from '../utils/const';
import { createFindErrorForIdentity, createValidateIdentity } from '../utils/validate';

/**
 * The group of data.
 */
export type Group = string;
/**
 * The type of data.
 */
export type Type = string;

/**
 * Represents the modality of a some data.
 */
export interface Modality {
  group: Group;
  type: Type;
}


// createValidateIdentity<Modality> creates a validator for the the elemental identity Modality
export const validateModality = createValidateIdentity<Modality>('modality');

export const ModalityProperties: Record<keyof Modality, PropertyDetails> = {
  "group": {
    "required": true,
    "description": "The group of data.",
    "title": "Group",
    "type": "string"
  },
  "type": {
    "required": true,
    "description": "The type of data.",
    "title": "Type",
    "type": "string"
  },
}

// ModalityIdentity
export const ModalityIdentity = {
  isIdentity: true,
  description: `Represents the modality of a some data.`,
  title: `Modality`,
  friendlyName: `Modality`,
  friendlyNamePlural: `Modalities`,
  name: 'Modality',
  restName: 'modality',
  resourceName: 'modalities',
  package: 'lain',
  archivable: false,
  findErrorForIdentity: createFindErrorForIdentity('modality'),
  properties: ModalityProperties,
} as const;
