// This file has been autogenerated using elemental cli. 
// Use `npm run sync` to update from latest elemental specifications

import { PropertyDetails } from '../utils/const';
import { createFindErrorForIdentity, createValidateIdentity } from '../utils/validate';

/**
 * Identification bit that will be used to identify the origin of the request.
 */
export type Name = string | null;

/**
 * Describes the principal information of a user.
 */
export interface PrincipalUser {
  name?: Name;
}


// createValidateIdentity<PrincipalUser> creates a validator for the the elemental identity PrincipalUser
export const validatePrincipalUser = createValidateIdentity<PrincipalUser>('principaluser');

export const PrincipalUserProperties: Record<keyof PrincipalUser, PropertyDetails> = {
  "name": {
    "description": "Identification bit that will be used to identify the origin of the request.",
    "title": "Name",
    "type": [
      "string",
      "null"
    ]
  },
}

// PrincipalUserIdentity
export const PrincipalUserIdentity = {
  isIdentity: true,
  description: `Describes the principal information of a user.`,
  title: `PrincipalUser`,
  friendlyName: `Principal User`,
  friendlyNamePlural: `Principal Users`,
  name: 'PrincipalUser',
  restName: 'principaluser',
  resourceName: 'principalusers',
  package: 'colektor',
  archivable: false,
  findErrorForIdentity: createFindErrorForIdentity('principaluser'),
  properties: PrincipalUserProperties,
} as const;
