// This file has been autogenerated using elemental cli. 
// Use `npm run sync` to update from latest elemental specifications

import { PropertyDetails } from '../utils/const';
import { createFindErrorForIdentity, createValidateIdentity } from '../utils/validate';

/**
 * root object.
 */
export interface Root {}


// createValidateIdentity<Root> creates a validator for the the elemental identity Root
export const validateRoot = createValidateIdentity<Root>('root');

export const RootProperties: Record<keyof Root, PropertyDetails> = {
}

// RootIdentity
export const RootIdentity = {
  isIdentity: true,
  description: `root object.`,
  title: `Root`,
  friendlyName: `Root`,
  friendlyNamePlural: `Roots`,
  name: 'Root',
  restName: 'root',
  resourceName: 'root',
  package: 'root',
  archivable: false,
  findErrorForIdentity: createFindErrorForIdentity('root'),
  properties: RootProperties,
} as const;
