guardrails:
  - name: secrets_detector
    matches:
      # example Optional redact: true, default redact: False
      credentials:
        redact: true
      # all possible secrets (redact default False)
      adafruit:
      alibaba:
      anthropic:
      apideck:
      apify:
      atlassian:
      aws_secret_key:
      buildkite:
      checkout:
      clickuppersonal:
      contentfulpersonalaccess:
      database_url_with_credentials:
      databricks:
      denodeploy:
      dfuse:
      digitalocean:
      discord_webhook:
      docker_hub:
      doppler:
      dropbox:
      endorlabs:
      fleetbase:
      flutterwave:
      frameio:
      freshdesk:
      fullstory:
      github:
      gitlab:
      gocardless:
      google_api:
      grafana:
      groq:
      huggingface:
      intra42:
      jwt:
      klaviyo:
      launchdarkly:
      linearapi:
      locationiq:
      mailchimp:
      mailgun:
      mapbox:
      maxmind:
      microsoft_teams_webhook:
      nightfall:
      notion:
      npm:
      openai:
      pagarme:
      paystack:
      planetscale:
      planetscaledb:
      portainer:
      posthog:
      postman:
      prefect:
      private_key:
      pubnub_publish:
      pubnub_subscribe:
      pulumi:
      ramp:
      razorpay:
      readme:
      rechargepayments:
      replicate:
      rubygems:
      salesforce:
      sendgrid:
      sendinblue:
      shopify:
      slack_access:
      slack_bot:
      slack_refresh:
      slack_user:
      slack_webhook:
      slack_workflow_webhook:
      sourcegraph:
      sourcegraphcody:
      squareapp:
      squareup:
      stripe:
      supabase:
      tailscale:
      tines_webhook:
      trufflehog:
      twilio:
      ubidots:
      voiceflow:
      web_url_with_credentials:
      zapierwebhook:
