/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The communication direction of the MCP message which can be from client to
 *
 * @remarks
 * server, or from server to client.
 */
export const Direction = {
  Client2Server: "Client2Server",
  Server2Client: "Server2Client",
} as const;
/**
 * The communication direction of the MCP message which can be from client to
 *
 * @remarks
 * server, or from server to client.
 */
export type Direction = ClosedEnum<typeof Direction>;

/**
 * The MCP message type which can be Request, Response or Notification.
 */
export const McpmessageType = {
  Request: "Request",
  Response: "Response",
  Notification: "Notification",
} as const;
/**
 * The MCP message type which can be Request, Response or Notification.
 */
export type McpmessageType = ClosedEnum<typeof McpmessageType>;

/**
 * Represents MCP message details.
 */
export type Mcpmessage = {
  /**
   * The communication direction of the MCP message which can be from client to
   *
   * @remarks
   * server, or from server to client.
   */
  direction: Direction;
  /**
   * IsError is true in case if a response is an error response as opposed to a
   *
   * @remarks
   * result. Note that this is not the same as a result which has isError set to true
   * within the result. This is a protocol level error. This will always be false for
   * requests and notifications, and false for reponses when the response has a
   * result.
   */
  isError?: boolean | undefined;
  /**
   * This is the method name of the request or notification. Contrary to MCP this is
   *
   * @remarks
   * set on responses as well if possible in which case the format will be of the
   * form method/params.name.
   */
  method?: string | undefined;
  /**
   * The ID of a request or a response. We always extract this as a string even
   *
   * @remarks
   * though this can be a string or number in MCP. It is derived from the id field of
   * a request or a response.
   */
  requestID?: string | undefined;
  /**
   * The session ID that this MCP message belongs to. This is strictly speaking not
   *
   * @remarks
   * part of MCP, and this can be empty.
   */
  sessionID?: string | undefined;
  /**
   * The MCP message type which can be Request, Response or Notification.
   */
  type: McpmessageType;
};

/** @internal */
export const Direction$inboundSchema: z.ZodNativeEnum<typeof Direction> = z
  .nativeEnum(Direction);

/** @internal */
export const Direction$outboundSchema: z.ZodNativeEnum<typeof Direction> =
  Direction$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Direction$ {
  /** @deprecated use `Direction$inboundSchema` instead. */
  export const inboundSchema = Direction$inboundSchema;
  /** @deprecated use `Direction$outboundSchema` instead. */
  export const outboundSchema = Direction$outboundSchema;
}

/** @internal */
export const McpmessageType$inboundSchema: z.ZodNativeEnum<
  typeof McpmessageType
> = z.nativeEnum(McpmessageType);

/** @internal */
export const McpmessageType$outboundSchema: z.ZodNativeEnum<
  typeof McpmessageType
> = McpmessageType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace McpmessageType$ {
  /** @deprecated use `McpmessageType$inboundSchema` instead. */
  export const inboundSchema = McpmessageType$inboundSchema;
  /** @deprecated use `McpmessageType$outboundSchema` instead. */
  export const outboundSchema = McpmessageType$outboundSchema;
}

/** @internal */
export const Mcpmessage$inboundSchema: z.ZodType<
  Mcpmessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  direction: Direction$inboundSchema,
  isError: z.boolean().optional(),
  method: z.string().optional(),
  requestID: z.string().optional(),
  sessionID: z.string().optional(),
  type: McpmessageType$inboundSchema,
});

/** @internal */
export type Mcpmessage$Outbound = {
  direction: string;
  isError?: boolean | undefined;
  method?: string | undefined;
  requestID?: string | undefined;
  sessionID?: string | undefined;
  type: string;
};

/** @internal */
export const Mcpmessage$outboundSchema: z.ZodType<
  Mcpmessage$Outbound,
  z.ZodTypeDef,
  Mcpmessage
> = z.object({
  direction: Direction$outboundSchema,
  isError: z.boolean().optional(),
  method: z.string().optional(),
  requestID: z.string().optional(),
  sessionID: z.string().optional(),
  type: McpmessageType$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Mcpmessage$ {
  /** @deprecated use `Mcpmessage$inboundSchema` instead. */
  export const inboundSchema = Mcpmessage$inboundSchema;
  /** @deprecated use `Mcpmessage$outboundSchema` instead. */
  export const outboundSchema = Mcpmessage$outboundSchema;
  /** @deprecated use `Mcpmessage$Outbound` instead. */
  export type Outbound = Mcpmessage$Outbound;
}

export function mcpmessageToJSON(mcpmessage: Mcpmessage): string {
  return JSON.stringify(Mcpmessage$outboundSchema.parse(mcpmessage));
}

export function mcpmessageFromJSON(
  jsonString: string,
): SafeParseResult<Mcpmessage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Mcpmessage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Mcpmessage' from JSON`,
  );
}
