/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents an MCP server object.
 */
export type Mcpserver = {
  /**
   * The allowed tools that the caller has access to. If empty, this means that the
   *
   * @remarks
   * caller has access to all tools provided by this MCP server.
   */
  allowedTools?: Array<string> | undefined;
  /**
   * The name of the MCP server.
   */
  name?: string | undefined;
  /**
   * The URL of the MCP server.
   */
  url: string;
};

/** @internal */
export const Mcpserver$inboundSchema: z.ZodType<
  Mcpserver,
  z.ZodTypeDef,
  unknown
> = z.object({
  allowedTools: z.array(z.string()).optional(),
  name: z.string().optional(),
  url: z.string(),
});

/** @internal */
export type Mcpserver$Outbound = {
  allowedTools?: Array<string> | undefined;
  name?: string | undefined;
  url: string;
};

/** @internal */
export const Mcpserver$outboundSchema: z.ZodType<
  Mcpserver$Outbound,
  z.ZodTypeDef,
  Mcpserver
> = z.object({
  allowedTools: z.array(z.string()).optional(),
  name: z.string().optional(),
  url: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Mcpserver$ {
  /** @deprecated use `Mcpserver$inboundSchema` instead. */
  export const inboundSchema = Mcpserver$inboundSchema;
  /** @deprecated use `Mcpserver$outboundSchema` instead. */
  export const outboundSchema = Mcpserver$outboundSchema;
  /** @deprecated use `Mcpserver$Outbound` instead. */
  export type Outbound = Mcpserver$Outbound;
}

export function mcpserverToJSON(mcpserver: Mcpserver): string {
  return JSON.stringify(Mcpserver$outboundSchema.parse(mcpserver));
}

export function mcpserverFromJSON(
  jsonString: string,
): SafeParseResult<Mcpserver, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Mcpserver$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Mcpserver' from JSON`,
  );
}
