/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents the tool annotations as they can be optionally defined for MCP tools.
 */
export type Mcptoolannotations = {
  /**
   * If true, the tool may perform destructive updates.
   */
  destructiveHint?: boolean | undefined;
  /**
   * If true, repeated calls with same args have no additional effect.
   */
  idempotentHint?: boolean | undefined;
  /**
   * If true, tool interacts with external entities.
   */
  openWorldHint?: boolean | undefined;
  /**
   * If true, the tool does not modify its environment.
   */
  readOnlyHint?: boolean | undefined;
  /**
   * Human-readable title for the tool.
   */
  title?: string | undefined;
};

/** @internal */
export const Mcptoolannotations$inboundSchema: z.ZodType<
  Mcptoolannotations,
  z.ZodTypeDef,
  unknown
> = z.object({
  destructiveHint: z.boolean().optional(),
  idempotentHint: z.boolean().optional(),
  openWorldHint: z.boolean().optional(),
  readOnlyHint: z.boolean().optional(),
  title: z.string().optional(),
});

/** @internal */
export type Mcptoolannotations$Outbound = {
  destructiveHint?: boolean | undefined;
  idempotentHint?: boolean | undefined;
  openWorldHint?: boolean | undefined;
  readOnlyHint?: boolean | undefined;
  title?: string | undefined;
};

/** @internal */
export const Mcptoolannotations$outboundSchema: z.ZodType<
  Mcptoolannotations$Outbound,
  z.ZodTypeDef,
  Mcptoolannotations
> = z.object({
  destructiveHint: z.boolean().optional(),
  idempotentHint: z.boolean().optional(),
  openWorldHint: z.boolean().optional(),
  readOnlyHint: z.boolean().optional(),
  title: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Mcptoolannotations$ {
  /** @deprecated use `Mcptoolannotations$inboundSchema` instead. */
  export const inboundSchema = Mcptoolannotations$inboundSchema;
  /** @deprecated use `Mcptoolannotations$outboundSchema` instead. */
  export const outboundSchema = Mcptoolannotations$outboundSchema;
  /** @deprecated use `Mcptoolannotations$Outbound` instead. */
  export type Outbound = Mcptoolannotations$Outbound;
}

export function mcptoolannotationsToJSON(
  mcptoolannotations: Mcptoolannotations,
): string {
  return JSON.stringify(
    Mcptoolannotations$outboundSchema.parse(mcptoolannotations),
  );
}

export function mcptoolannotationsFromJSON(
  jsonString: string,
): SafeParseResult<Mcptoolannotations, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Mcptoolannotations$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Mcptoolannotations' from JSON`,
  );
}
