/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Describes the optional principal information of the user of an application which
 *
 * @remarks
 * is being derived from a bearer token of a request.
 */
export type Principalappuser = {
  /**
   * The Email address of the user. This will be derived from the email claims of a
   *
   * @remarks
   * token like email, emailAddress or upn.
   */
  email?: string | undefined;
  /**
   * The given name of the user. This will be derived from the common name claims of
   *
   * @remarks
   * a token like name or given_name.
   */
  name?: string | undefined;
  /**
   * This will be true if the apex was able to validate the token in the request.
   */
  tokenValidated?: boolean | undefined;
};

/** @internal */
export const Principalappuser$inboundSchema: z.ZodType<
  Principalappuser,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string().optional(),
  name: z.string().optional(),
  tokenValidated: z.boolean().optional(),
});

/** @internal */
export type Principalappuser$Outbound = {
  email?: string | undefined;
  name?: string | undefined;
  tokenValidated?: boolean | undefined;
};

/** @internal */
export const Principalappuser$outboundSchema: z.ZodType<
  Principalappuser$Outbound,
  z.ZodTypeDef,
  Principalappuser
> = z.object({
  email: z.string().optional(),
  name: z.string().optional(),
  tokenValidated: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Principalappuser$ {
  /** @deprecated use `Principalappuser$inboundSchema` instead. */
  export const inboundSchema = Principalappuser$inboundSchema;
  /** @deprecated use `Principalappuser$outboundSchema` instead. */
  export const outboundSchema = Principalappuser$outboundSchema;
  /** @deprecated use `Principalappuser$Outbound` instead. */
  export type Outbound = Principalappuser$Outbound;
}

export function principalappuserToJSON(
  principalappuser: Principalappuser,
): string {
  return JSON.stringify(
    Principalappuser$outboundSchema.parse(principalappuser),
  );
}

export function principalappuserFromJSON(
  jsonString: string,
): SafeParseResult<Principalappuser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Principalappuser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Principalappuser' from JSON`,
  );
}
