/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Alertevent,
  Alertevent$inboundSchema,
  Alertevent$Outbound,
  Alertevent$outboundSchema,
} from "./alertevent.js";
import {
  Extraction,
  Extraction$inboundSchema,
  Extraction$Outbound,
  Extraction$outboundSchema,
} from "./extraction.js";
import {
  Extractionsummary,
  Extractionsummary$inboundSchema,
  Extractionsummary$Outbound,
  Extractionsummary$outboundSchema,
} from "./extractionsummary.js";
import {
  Latency,
  Latency$inboundSchema,
  Latency$Outbound,
  Latency$outboundSchema,
} from "./latency.js";
import {
  Principal,
  Principal$inboundSchema,
  Principal$Outbound,
  Principal$outboundSchema,
} from "./principal.js";

/**
 * Tell what was the decision about the data.
 */
export const Decision = {
  Deny: "Deny",
  Allow: "Allow",
  Ask: "Ask",
  Bypassed: "Bypassed",
  ForbiddenUser: "ForbiddenUser",
} as const;
/**
 * Tell what was the decision about the data.
 */
export type Decision = ClosedEnum<typeof Decision>;

/**
 * The type of text.
 */
export const ScanresponseType = {
  Input: "Input",
  Output: "Output",
} as const;
/**
 * The type of text.
 */
export type ScanresponseType = ClosedEnum<typeof ScanresponseType>;

/**
 * This is a scan response.
 */
export type Scanresponse = {
  /**
   * ID is the identifier of the object.
   */
  id?: string | undefined;
  /**
   * List of alerts that got raised during the policy resolution.
   */
  alerts?: Array<Alertevent> | undefined;
  /**
   * Annotations attached to the log.
   */
  annotations?: { [k: string]: string } | undefined;
  /**
   * The client used to send the request.
   */
  client?: string | undefined;
  /**
   * The version of the client used to send the request.
   */
  clientVersion?: string | undefined;
  /**
   * Tell what was the decision about the data.
   */
  decision?: Decision | undefined;
  /**
   * The extractions to log.
   */
  extractions?: Array<Extraction> | undefined;
  /**
   * The hash of the input.
   */
  hash?: string | undefined;
  /**
   * Holds information about latencies introduced by Apex.
   */
  latency?: Latency | undefined;
  /**
   * The namespace of the object.
   */
  namespace?: string | undefined;
  /**
   * The name of the particular pipeline that extracted the text.
   */
  pipelineName?: string | undefined;
  /**
   * Describe the principal.
   */
  principal: Principal;
  /**
   * the provider to use.
   */
  provider?: string | undefined;
  /**
   * The various reasons returned by the policy engine.
   */
  reasons?: Array<string> | undefined;
  /**
   * Represents the summary of the extractions.
   */
  summary?: Extractionsummary | undefined;
  /**
   * Set the time of the message request.
   */
  time?: Date | undefined;
  /**
   * The type of text.
   */
  type?: ScanresponseType | undefined;
};

/** @internal */
export const Decision$inboundSchema: z.ZodNativeEnum<typeof Decision> = z
  .nativeEnum(Decision);

/** @internal */
export const Decision$outboundSchema: z.ZodNativeEnum<typeof Decision> =
  Decision$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Decision$ {
  /** @deprecated use `Decision$inboundSchema` instead. */
  export const inboundSchema = Decision$inboundSchema;
  /** @deprecated use `Decision$outboundSchema` instead. */
  export const outboundSchema = Decision$outboundSchema;
}

/** @internal */
export const ScanresponseType$inboundSchema: z.ZodNativeEnum<
  typeof ScanresponseType
> = z.nativeEnum(ScanresponseType);

/** @internal */
export const ScanresponseType$outboundSchema: z.ZodNativeEnum<
  typeof ScanresponseType
> = ScanresponseType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ScanresponseType$ {
  /** @deprecated use `ScanresponseType$inboundSchema` instead. */
  export const inboundSchema = ScanresponseType$inboundSchema;
  /** @deprecated use `ScanresponseType$outboundSchema` instead. */
  export const outboundSchema = ScanresponseType$outboundSchema;
}

/** @internal */
export const Scanresponse$inboundSchema: z.ZodType<
  Scanresponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ID: z.string().optional(),
  alerts: z.array(Alertevent$inboundSchema).optional(),
  annotations: z.record(z.string()).optional(),
  client: z.string().optional(),
  clientVersion: z.string().optional(),
  decision: Decision$inboundSchema.optional(),
  extractions: z.array(Extraction$inboundSchema).optional(),
  hash: z.string().optional(),
  latency: Latency$inboundSchema.optional(),
  namespace: z.string().optional(),
  pipelineName: z.string().optional(),
  principal: Principal$inboundSchema,
  provider: z.string().optional(),
  reasons: z.array(z.string()).optional(),
  summary: Extractionsummary$inboundSchema.optional(),
  time: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  type: ScanresponseType$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ID": "id",
  });
});

/** @internal */
export type Scanresponse$Outbound = {
  ID?: string | undefined;
  alerts?: Array<Alertevent$Outbound> | undefined;
  annotations?: { [k: string]: string } | undefined;
  client?: string | undefined;
  clientVersion?: string | undefined;
  decision?: string | undefined;
  extractions?: Array<Extraction$Outbound> | undefined;
  hash?: string | undefined;
  latency?: Latency$Outbound | undefined;
  namespace?: string | undefined;
  pipelineName?: string | undefined;
  principal: Principal$Outbound;
  provider?: string | undefined;
  reasons?: Array<string> | undefined;
  summary?: Extractionsummary$Outbound | undefined;
  time?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const Scanresponse$outboundSchema: z.ZodType<
  Scanresponse$Outbound,
  z.ZodTypeDef,
  Scanresponse
> = z.object({
  id: z.string().optional(),
  alerts: z.array(Alertevent$outboundSchema).optional(),
  annotations: z.record(z.string()).optional(),
  client: z.string().optional(),
  clientVersion: z.string().optional(),
  decision: Decision$outboundSchema.optional(),
  extractions: z.array(Extraction$outboundSchema).optional(),
  hash: z.string().optional(),
  latency: Latency$outboundSchema.optional(),
  namespace: z.string().optional(),
  pipelineName: z.string().optional(),
  principal: Principal$outboundSchema,
  provider: z.string().optional(),
  reasons: z.array(z.string()).optional(),
  summary: Extractionsummary$outboundSchema.optional(),
  time: z.date().transform(v => v.toISOString()).optional(),
  type: ScanresponseType$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    id: "ID",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Scanresponse$ {
  /** @deprecated use `Scanresponse$inboundSchema` instead. */
  export const inboundSchema = Scanresponse$inboundSchema;
  /** @deprecated use `Scanresponse$outboundSchema` instead. */
  export const outboundSchema = Scanresponse$outboundSchema;
  /** @deprecated use `Scanresponse$Outbound` instead. */
  export type Outbound = Scanresponse$Outbound;
}

export function scanresponseToJSON(scanresponse: Scanresponse): string {
  return JSON.stringify(Scanresponse$outboundSchema.parse(scanresponse));
}

export function scanresponseFromJSON(
  jsonString: string,
): SafeParseResult<Scanresponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Scanresponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Scanresponse' from JSON`,
  );
}
