/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * ScanExternalUser holds the information about the remote user for a ScanRequest.
 */
export type Scanexternaluser = {
  /**
   * List of claims extracted from the user query.
   */
  claims: Array<string>;
  /**
   * The name of the external user.
   */
  name: string;
};

/** @internal */
export const Scanexternaluser$inboundSchema: z.ZodType<
  Scanexternaluser,
  z.ZodTypeDef,
  unknown
> = z.object({
  claims: z.array(z.string()),
  name: z.string(),
});

/** @internal */
export type Scanexternaluser$Outbound = {
  claims: Array<string>;
  name: string;
};

/** @internal */
export const Scanexternaluser$outboundSchema: z.ZodType<
  Scanexternaluser$Outbound,
  z.ZodTypeDef,
  Scanexternaluser
> = z.object({
  claims: z.array(z.string()),
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Scanexternaluser$ {
  /** @deprecated use `Scanexternaluser$inboundSchema` instead. */
  export const inboundSchema = Scanexternaluser$inboundSchema;
  /** @deprecated use `Scanexternaluser$outboundSchema` instead. */
  export const outboundSchema = Scanexternaluser$outboundSchema;
  /** @deprecated use `Scanexternaluser$Outbound` instead. */
  export type Outbound = Scanexternaluser$Outbound;
}

export function scanexternaluserToJSON(
  scanexternaluser: Scanexternaluser,
): string {
  return JSON.stringify(
    Scanexternaluser$outboundSchema.parse(scanexternaluser),
  );
}

export function scanexternaluserFromJSON(
  jsonString: string,
): SafeParseResult<Scanexternaluser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Scanexternaluser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Scanexternaluser' from JSON`,
  );
}
