/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents the tool result as passed in by the user or application after calling
 *
 * @remarks
 * a tool.
 */
export type Toolresult = {
  /**
   * The ID of the tool use as previously returned by a models tool use response.
   */
  callID: string;
  /**
   * The content of the tool call results.
   */
  content?: string | undefined;
  /**
   * Indicates if the tool call failed.
   */
  isError?: boolean | undefined;
};

/** @internal */
export const Toolresult$inboundSchema: z.ZodType<
  Toolresult,
  z.ZodTypeDef,
  unknown
> = z.object({
  callID: z.string(),
  content: z.string().optional(),
  isError: z.boolean().default(false),
});

/** @internal */
export type Toolresult$Outbound = {
  callID: string;
  content?: string | undefined;
  isError: boolean;
};

/** @internal */
export const Toolresult$outboundSchema: z.ZodType<
  Toolresult$Outbound,
  z.ZodTypeDef,
  Toolresult
> = z.object({
  callID: z.string(),
  content: z.string().optional(),
  isError: z.boolean().default(false),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Toolresult$ {
  /** @deprecated use `Toolresult$inboundSchema` instead. */
  export const inboundSchema = Toolresult$inboundSchema;
  /** @deprecated use `Toolresult$outboundSchema` instead. */
  export const outboundSchema = Toolresult$outboundSchema;
  /** @deprecated use `Toolresult$Outbound` instead. */
  export type Outbound = Toolresult$Outbound;
}

export function toolresultToJSON(toolresult: Toolresult): string {
  return JSON.stringify(Toolresult$outboundSchema.parse(toolresult));
}

export function toolresultFromJSON(
  jsonString: string,
): SafeParseResult<Toolresult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Toolresult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Toolresult' from JSON`,
  );
}
