/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Model instructions on tool choice.
 */
export const Choice = {
  Auto: "Auto",
  Any: "Any",
  None: "None",
  Tool: "Tool",
} as const;
/**
 * Model instructions on tool choice.
 */
export type Choice = ClosedEnum<typeof Choice>;

/**
 * Represents the tool choice that can be passed along together with tools.
 */
export type Toolchoice = {
  /**
   * Model instructions on tool choice.
   */
  choice?: Choice | undefined;
  /**
   * If choice is Tool, this will be set to the name of the tool to use.
   */
  name?: string | undefined;
};

/** @internal */
export const Choice$inboundSchema: z.ZodNativeEnum<typeof Choice> = z
  .nativeEnum(Choice);

/** @internal */
export const Choice$outboundSchema: z.ZodNativeEnum<typeof Choice> =
  Choice$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Choice$ {
  /** @deprecated use `Choice$inboundSchema` instead. */
  export const inboundSchema = Choice$inboundSchema;
  /** @deprecated use `Choice$outboundSchema` instead. */
  export const outboundSchema = Choice$outboundSchema;
}

/** @internal */
export const Toolchoice$inboundSchema: z.ZodType<
  Toolchoice,
  z.ZodTypeDef,
  unknown
> = z.object({
  choice: Choice$inboundSchema.default("Auto"),
  name: z.string().optional(),
});

/** @internal */
export type Toolchoice$Outbound = {
  choice: string;
  name?: string | undefined;
};

/** @internal */
export const Toolchoice$outboundSchema: z.ZodType<
  Toolchoice$Outbound,
  z.ZodTypeDef,
  Toolchoice
> = z.object({
  choice: Choice$outboundSchema.default("Auto"),
  name: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Toolchoice$ {
  /** @deprecated use `Toolchoice$inboundSchema` instead. */
  export const inboundSchema = Toolchoice$inboundSchema;
  /** @deprecated use `Toolchoice$outboundSchema` instead. */
  export const outboundSchema = Toolchoice$outboundSchema;
  /** @deprecated use `Toolchoice$Outbound` instead. */
  export type Outbound = Toolchoice$Outbound;
}

export function toolchoiceToJSON(toolchoice: Toolchoice): string {
  return JSON.stringify(Toolchoice$outboundSchema.parse(toolchoice));
}

export function toolchoiceFromJSON(
  jsonString: string,
): SafeParseResult<Toolchoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Toolchoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Toolchoice' from JSON`,
  );
}
