/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Represents the tool use which are instructions by a model on what tool to call
 *
 * @remarks
 * and how.
 */
export type Tooluse = {
  /**
   * The ID of the tool use which the user or application must pass when posting back
   *
   * @remarks
   * the tool call results.
   */
  callID: string;
  /**
   * The input to the tool call. This should be a JSON object which must conform to
   *
   * @remarks
   * the JSON schema as was previously defined for the tool.
   */
  input?: string | undefined;
  /**
   * The name of the tool to call.
   */
  name: string;
  /**
   * The name of the remote MCP server that will execute this call.
   */
  serverName?: string | undefined;
};

/** @internal */
export const Tooluse$inboundSchema: z.ZodType<Tooluse, z.ZodTypeDef, unknown> =
  z.object({
    callID: z.string(),
    input: z.string().optional(),
    name: z.string(),
    serverName: z.string().optional(),
  });

/** @internal */
export type Tooluse$Outbound = {
  callID: string;
  input?: string | undefined;
  name: string;
  serverName?: string | undefined;
};

/** @internal */
export const Tooluse$outboundSchema: z.ZodType<
  Tooluse$Outbound,
  z.ZodTypeDef,
  Tooluse
> = z.object({
  callID: z.string(),
  input: z.string().optional(),
  name: z.string(),
  serverName: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Tooluse$ {
  /** @deprecated use `Tooluse$inboundSchema` instead. */
  export const inboundSchema = Tooluse$inboundSchema;
  /** @deprecated use `Tooluse$outboundSchema` instead. */
  export const outboundSchema = Tooluse$outboundSchema;
  /** @deprecated use `Tooluse$Outbound` instead. */
  export type Outbound = Tooluse$Outbound;
}

export function tooluseToJSON(tooluse: Tooluse): string {
  return JSON.stringify(Tooluse$outboundSchema.parse(tooluse));
}

export function tooluseFromJSON(
  jsonString: string,
): SafeParseResult<Tooluse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tooluse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tooluse' from JSON`,
  );
}
