/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Mcpserver,
  Mcpserver$inboundSchema,
  Mcpserver$Outbound,
  Mcpserver$outboundSchema,
} from "./mcpserver.js";
import {
  Mcptoolannotations,
  Mcptoolannotations$inboundSchema,
  Mcptoolannotations$Outbound,
  Mcptoolannotations$outboundSchema,
} from "./mcptoolannotations.js";

/**
 * The category of the tool. This relays information about where the tool is being
 *
 * @remarks
 * used. This can be empty if unknown or if this is a tool listing of MCP servers.
 */
export const Category = {
  Client: "Client",
  Server: "Server",
  RemoteMCP: "RemoteMCP",
} as const;
/**
 * The category of the tool. This relays information about where the tool is being
 *
 * @remarks
 * used. This can be empty if unknown or if this is a tool listing of MCP servers.
 */
export type Category = ClosedEnum<typeof Category>;

/**
 * Represents a tool that can enhance a genAI model's capabilities.
 */
export type Tool = {
  /**
   * Represents the tool annotations as they can be optionally defined for MCP tools.
   */
  mcpAnnotations?: Mcptoolannotations | undefined;
  /**
   * Represents an MCP server object.
   */
  mcpServer?: Mcpserver | undefined;
  /**
   * The category of the tool. This relays information about where the tool is being
   *
   * @remarks
   * used. This can be empty if unknown or if this is a tool listing of MCP servers.
   */
  category?: Category | undefined;
  /**
   * The description of the tool.
   */
  description?: string | undefined;
  /**
   * The name of the tool.
   */
  name?: string | undefined;
  /**
   * The type of the tool as can be optionally passed by the provider.
   */
  type?: string | undefined;
};

/** @internal */
export const Category$inboundSchema: z.ZodNativeEnum<typeof Category> = z
  .nativeEnum(Category);

/** @internal */
export const Category$outboundSchema: z.ZodNativeEnum<typeof Category> =
  Category$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Category$ {
  /** @deprecated use `Category$inboundSchema` instead. */
  export const inboundSchema = Category$inboundSchema;
  /** @deprecated use `Category$outboundSchema` instead. */
  export const outboundSchema = Category$outboundSchema;
}

/** @internal */
export const Tool$inboundSchema: z.ZodType<Tool, z.ZodTypeDef, unknown> = z
  .object({
    MCPAnnotations: Mcptoolannotations$inboundSchema.optional(),
    MCPServer: Mcpserver$inboundSchema.optional(),
    category: Category$inboundSchema.optional(),
    description: z.string().optional(),
    name: z.string().optional(),
    type: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "MCPAnnotations": "mcpAnnotations",
      "MCPServer": "mcpServer",
    });
  });

/** @internal */
export type Tool$Outbound = {
  MCPAnnotations?: Mcptoolannotations$Outbound | undefined;
  MCPServer?: Mcpserver$Outbound | undefined;
  category?: string | undefined;
  description?: string | undefined;
  name?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const Tool$outboundSchema: z.ZodType<Tool$Outbound, z.ZodTypeDef, Tool> =
  z.object({
    mcpAnnotations: Mcptoolannotations$outboundSchema.optional(),
    mcpServer: Mcpserver$outboundSchema.optional(),
    category: Category$outboundSchema.optional(),
    description: z.string().optional(),
    name: z.string().optional(),
    type: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      mcpAnnotations: "MCPAnnotations",
      mcpServer: "MCPServer",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Tool$ {
  /** @deprecated use `Tool$inboundSchema` instead. */
  export const inboundSchema = Tool$inboundSchema;
  /** @deprecated use `Tool$outboundSchema` instead. */
  export const outboundSchema = Tool$outboundSchema;
  /** @deprecated use `Tool$Outbound` instead. */
  export type Outbound = Tool$Outbound;
}

export function toolToJSON(tool: Tool): string {
  return JSON.stringify(Tool$outboundSchema.parse(tool));
}

export function toolFromJSON(
  jsonString: string,
): SafeParseResult<Tool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tool' from JSON`,
  );
}
