/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The kind of the span.
 */
export const Kind = {
  Unspecified: "Unspecified",
  Internal: "Internal",
  Server: "Server",
  Client: "Client",
  Producer: "Producer",
  Consumer: "Consumer",
} as const;
/**
 * The kind of the span.
 */
export type Kind = ClosedEnum<typeof Kind>;

/**
 * Status Code of a span.
 */
export const StatusCode = {
  Unset: "Unset",
  Ok: "OK",
  Error: "Error",
} as const;
/**
 * Status Code of a span.
 */
export type StatusCode = ClosedEnum<typeof StatusCode>;

/**
 * Holds all references to a trace which are also the essentials of the span data.
 */
export type Traceref = {
  /**
   * The kind of the span.
   */
  kind?: Kind | undefined;
  /**
   * The parent span ID that is being referenced as hex encoded string.
   */
  parentSpanID?: string | undefined;
  /**
   * When the span ended.
   */
  spanEnd: Date;
  /**
   * The span ID that is being referenced.
   */
  spanID: string;
  /**
   * The name of the span that is being collected.
   */
  spanName: string;
  /**
   * When the span started.
   */
  spanStart: Date;
  /**
   * Status Code of a span.
   */
  statusCode?: StatusCode | undefined;
  /**
   * A developer-facing human readable error message.
   */
  statusMessage?: string | undefined;
  /**
   * The Trace ID that is being referenced as hex encoded string.
   */
  traceID: string;
  /**
   * The transparent span ID that is being referenced. If the application operates in
   *
   * @remarks
   * transparent tracing mode, then this field must be set to the span ID that this
   * span is originally referencing.
   */
  transparentSpanID?: string | undefined;
};

/** @internal */
export const Kind$inboundSchema: z.ZodNativeEnum<typeof Kind> = z.nativeEnum(
  Kind,
);

/** @internal */
export const Kind$outboundSchema: z.ZodNativeEnum<typeof Kind> =
  Kind$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Kind$ {
  /** @deprecated use `Kind$inboundSchema` instead. */
  export const inboundSchema = Kind$inboundSchema;
  /** @deprecated use `Kind$outboundSchema` instead. */
  export const outboundSchema = Kind$outboundSchema;
}

/** @internal */
export const StatusCode$inboundSchema: z.ZodNativeEnum<typeof StatusCode> = z
  .nativeEnum(StatusCode);

/** @internal */
export const StatusCode$outboundSchema: z.ZodNativeEnum<typeof StatusCode> =
  StatusCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StatusCode$ {
  /** @deprecated use `StatusCode$inboundSchema` instead. */
  export const inboundSchema = StatusCode$inboundSchema;
  /** @deprecated use `StatusCode$outboundSchema` instead. */
  export const outboundSchema = StatusCode$outboundSchema;
}

/** @internal */
export const Traceref$inboundSchema: z.ZodType<
  Traceref,
  z.ZodTypeDef,
  unknown
> = z.object({
  kind: Kind$inboundSchema.default("Unspecified"),
  parentSpanID: z.string().optional(),
  spanEnd: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  spanID: z.string(),
  spanName: z.string(),
  spanStart: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  statusCode: StatusCode$inboundSchema.default("Unset"),
  statusMessage: z.string().optional(),
  traceID: z.string(),
  transparentSpanID: z.string().optional(),
});

/** @internal */
export type Traceref$Outbound = {
  kind: string;
  parentSpanID?: string | undefined;
  spanEnd: string;
  spanID: string;
  spanName: string;
  spanStart: string;
  statusCode: string;
  statusMessage?: string | undefined;
  traceID: string;
  transparentSpanID?: string | undefined;
};

/** @internal */
export const Traceref$outboundSchema: z.ZodType<
  Traceref$Outbound,
  z.ZodTypeDef,
  Traceref
> = z.object({
  kind: Kind$outboundSchema.default("Unspecified"),
  parentSpanID: z.string().optional(),
  spanEnd: z.date().transform(v => v.toISOString()),
  spanID: z.string(),
  spanName: z.string(),
  spanStart: z.date().transform(v => v.toISOString()),
  statusCode: StatusCode$outboundSchema.default("Unset"),
  statusMessage: z.string().optional(),
  traceID: z.string(),
  transparentSpanID: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Traceref$ {
  /** @deprecated use `Traceref$inboundSchema` instead. */
  export const inboundSchema = Traceref$inboundSchema;
  /** @deprecated use `Traceref$outboundSchema` instead. */
  export const outboundSchema = Traceref$outboundSchema;
  /** @deprecated use `Traceref$Outbound` instead. */
  export type Outbound = Traceref$Outbound;
}

export function tracerefToJSON(traceref: Traceref): string {
  return JSON.stringify(Traceref$outboundSchema.parse(traceref));
}

export function tracerefFromJSON(
  jsonString: string,
): SafeParseResult<Traceref, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Traceref$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Traceref' from JSON`,
  );
}
