# This runs on
# - Push to main
# - PRs
name: test
on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

env:
  ACUVITY_TOKEN: ${{ secrets.ACUVITY_TOKEN }}

jobs:
  sanity:
    name: Sanity
    runs-on: ubuntu-latest
    concurrency:
      group: matrix-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm install
          npm run build

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'Adding Bun to PATH'
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun installation
        run: bun --version

      - name: Install Deno
        run: |
          curl -fsSL https://deno.land/install.sh | bash
          echo 'export PATH="$HOME/.deno/bin:$PATH"' >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Verify Deno installation
        run: deno --version

      - name: Link
        run: |
          npm link

      - name: test
        run: |
          echo "Running all tests ..."
          npx jest --debug

      - name: Run examples
        run: |
          cd examples
          npm link @acuvity/acuvity
          echo "Running all examples ..."
          ./run.sh
